name: formteaapp
description: A new Flutter project.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  sqflite: ^2.4.2
  path: ^1.8.0
  http: ^1.5.0
  xml: ^6.5.0
  image_picker: ^1.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  kakao_flutter_sdk: ^1.9.7+3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/kakao.png
    - assets/google.png
    - assets/naver.png
